name: first_workflow  #name of the workflow
on:                   #when it will automate
  push:              
    branches:
      main
      dev
  pull_request: 
    branches: 
      main
  #schedule: 
   # - cron: '*/10 * * * 4'
     

jobs:                 #workflow define 
  job1: 
    runs-on: ubuntu-latest #server where it will run
    steps:                 # workflow steps 
    - name: step1
      run: echo "hello from step1, workflow job1"
    - name: step2
      run: echo " hello, i am sahil"
    - run: echo " hello from step3"
    - name: step4 
      run: |
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
  job2: 
    runs-on: sahil #server where it will run
    steps:                 # workflow steps 
    - name: step1
      run: echo "hello from step1, workflow job2"
    - name: step2
      run: echo " hello, i am sahil"
    - run: echo " hello from step3"
    - name: step4 
      run: |
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
