name: first_workflow  #name of the workflow
on:                   #when it will automate
  push:              
    branches:
      - main
      - dev
  pull_request: 
    branches: 
      - main
  #schedule: 
   # - cron: '*/10 * * * 4'
  workflow_dispatch:
env: 
  name: sahil
  lastname: jangra

jobs:                 #workflow define 
  job1: 
    env: 
      work: build
    runs-on: ubuntu-latest #server where it will run
    steps:                 # workflow steps 
    - name: step1
      run: echo "hello from $name, workflow $work in repo ${{ github.repository }} on runner os ${{ runner.os }} "
    - name: step2
      run: echo " hello, i am $name"
    - run: echo " hello from step3"
    - name: step4 
      run: |
      if: runner.os == 'windows'
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
  job2: 
    if: runner.os == 'windows'
    env: 
      work: test
    runs-on: ubuntu-latest #server where it will run
    steps:                 # workflow steps 
    - name: step1
      run: echo "hello from $name, workflow $work in repo ${{ github.repository }} on runner os ${{runner.os}} "
    - name: step2
      run: echo " hello, i am $name"
    - run: echo " hello from step3"
    - name: step4 
      run: |
          ls -l
          pwd
          sudo cat /etc/os-release
          uname -a
          echo "final step4 execution done"
