name: first_workflow  #name of the workflow
on: push              #when it will automate

jobs:                 #workflow define 
  job1: 
    runs-on: ubuntu-latest #server where it will run
    steps:                 # workflow steps 
    - name: step1
      run: echo "hello from step1, workflow step1"
